accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns =[
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('profile/<int:user_id>', views.profile_view, name='profile'),
    path('follow/<int:user_id>', views.follow_view, name='follow'),
]

products/urls.py
from django.urls import path
from products import views
from django.conf import settings
from django.conf.urls.static import static
from .views import create_view, update_view


app_name = 'products'


urlpatterns =[
    path("", views.list_view, name="list"),
    path("<int:product_id>", views.detail_view, name="detail"),
    path("create/", views.create_view, name="create"),
    path("update/<int:product_id>", views.update_view, name="update"),
    path("delete/<int:product_id>", views.delete_view, name="delete"),
    path("choose/<int:product_id>", views.choose_view, name='choose'),
    path('product/new/', create_view, name='product_new'),
    path('product/<int:pk>/edit/', update_view, name='product_edit'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sparta_maket/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('products.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):

    choose_products = models.ManyToManyField('products.Product', related_name='choose_users')
    followers = models.ManyToManyField('accounts.User', related_name='followings')
    

products/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    price = models.PositiveIntegerField()
    author = models.ForeignKey('accounts.User', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/', blank=True, null=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from accounts.models import User


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)

products/forms.py
from django import forms
from products.models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['title', 'content', 'price', 'image']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '너의 이름'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': '설명'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': '가격'})
        }
        


    def save(self, commit=True):
        instance = super().save(commit=False)
        
        if commit:
            instance.save()
        return instance
        

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404,redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.views.decorators.http import require_POST
from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm
from accounts.models import User
from django.contrib.auth.decorators import login_required


def login_view(request):
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(request.GET.get('next') or 'products:list')
        messages.error(request,'이게 맞을까요?')
    return render(request,'accounts/login.html')

@require_POST
def logout_view(request):
    logout(request)
    return redirect("products:list")



def signup_view(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('products:list')
    
    context = {
        'form':form,
    }
    return render(request,'accounts/signup.html', context)

def profile_view(request, user_id):
    user = get_object_or_404(User, id=user_id)
    return render(request, 'accounts/profile.html', {'profile_user': user})

@login_required
@require_POST
def follow_view(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if user.followers.filter(id=request.user.id).exists():
        user.followers.remove(request.user)
    else:
        user.followers.add(request.user)
    return redirect('accounts:profile', user_id=user_id)

products/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse
from products.forms import ProductForm
from products.models import Product
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User

def list_view(request):
    products = Product.objects.all()
    return render(request, "products/list.html", {"products": products})

@login_required
def create_view(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES)  
        if form.is_valid():
            product = form.save(commit=False)
            product.author = request.user  
            product.save()
            return redirect("products:list")
    else:
        form = ProductForm()
    return render(request, "products/create.html", {'form': form})

def detail_view(request,product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, "products/detail.html", {"product": product})

@login_required
def update_view(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    
    
    if product.author != request.user:
        return redirect("products:detail", product_id=product_id)

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            updated_product = form.save(commit=False)  
            updated_product.author = request.user      
            updated_product.save()               
            return redirect("products:list")
    else:
        form = ProductForm(instance=product)

    return render(request, "products/create.html", {"form": form})


@login_required
@require_POST
def delete_view(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if product.author != request.user:
        messages.warning(request,"작성자 본인만 수정")
        return redirect("products:detail", product_id=product_id)
    product.delete()
    return redirect("products:list")


@login_required
@require_POST
def choose_view(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    user: User = request.user
    if user.choose_products.filter(id=product_id).exists():
        user.choose_products.remove(product)
    else:
        user.choose_products.add(product)
    return redirect('products:list')

def upload_image(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('some_view')
    else:
        form = ProductForm()
    return render(request, 'upload_image.html', {'form': form})

accounts/templates/accounts/login.html
{% extends "base.html" %}


{% block  content %}
    <h1>login</h1>
    <form action="" method="POST">
    {% csrf_token %}
        <input type="text" name="username"><br>
        <input type="password" name="password" >
        <button>로그인</button>

    </form>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}


{% block  content %}
    <h2 style="color: rgb(255, 104, 104);">{{ profile_user.username }}어서와라 너의 프로필이다!</h2>

    <p style="color: rgb(255, 214, 125);">가입일 : {{ profile_user.date_joined}}</p>
    <p style="color: rgb(255, 243, 138);"> 팔로잉 : {{ profile_user.followers.count }}

    <form action="{% url 'accounts:follow' profile_user.id %}" method="POST">
        {% csrf_token %}
        {% if request.user in profile_user.followers.all %}
            <button>팔로우 해제</button>
        {% else %}
            <button>팔로우</button>
        {% endif %}
    </form>

    <h3 style="color: rgb(220, 113, 235);">등록 물건</h3>
    <ul>
        {% for choose_product in profile_user.product_set.all %}
        <li>
            <a href="{% url 'products:detail' choose_product.id %}" style="color: rgb(84, 253, 197);">
                {{ choose_product.id}}. {{ choose_product.tittle }}
            </a>
        </li>
    {% endfor %}
    </ul>
    

    <h2 style="color: rgb(220, 113, 235);">찜 목록</h2>
    <ul>
        {% for choose_product in profile_user.choose_products.all %}
        <li>
            <a href="{% url 'products:detail' choose_product.id %}" style="color: rgb(84, 253, 197);">
                {{ choose_product.id}}. {{ choose_product.tittle }}
            </a>
        </li>
    {% endfor %}
    </ul>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block  content %}
    <h1 style="color: white;">signup</h1>
    <style>
        .highlight {
            color: blue; /* 글자 색상을 파란색으로 설정 */
        }
        .form-label {
            color: white; /* 폼 라벨의 글자 색상을 녹색으로 설정 */
        }
    </style>
    <form action="" method="POST">
        {% csrf_token %}
        <label class="form-label">{{ form }}</label>
        <button>로그인</button>

    </form>

{% endblock content %}

products/templates/products/create.html
{% extends 'base.html' %}


{% block content %}
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
    <button>작성하기1</button><br>
    </form>
{% endblock content %}

products/templates/products/detail.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}

{% if article.image %}
		<img src="{{ article.image.url }}">
{% endif %}	

   <h1>{{ product.title }}</h1> 
   <p>{{ product.price|intcomma }}원</p>
   <div>{{ product.content }}</div>
   <br>
   <a href="{% url 'products:update' product.id %}">수정</a>
   <form action="{% url 'products:delete' product.id %}", method="POST">
      {% csrf_token %}
      <button type="submit">삭제</button>
   {% if product.image %}
   <img src="{{ product.image.url }}">
   {% endif %}
   </form>
{% endblock content %}

products/templates/products/list.html
{% extends 'base.html' %}
{% load humanize static %}


{% block content %}
    <a href="{% url 'products:create' %}" style="color: rgb(255, 255, 255);">글 작성</a>
    <br>
    {% for product in products %}
    <br>
        <div>
            <a href="{% url 'products:detail' product.id %}">
                {% if product.image %}
                    <img src="{{ product.image.url }}" alt="{{ product.title }}" style="width: 170px; height: auto;">
                {% endif %}
                <div style="color: rgb(253, 107, 241);">{{ product.id }}. {{ product.title }}</div>
                <div style="color: lightgreen;">{{ product.price|intcomma }}</div>
            </a>
            <form action="{% url 'products:choose' product.id %}"method ='POST'>
                {% csrf_token %}
                <button style="background-color: lightgoldenrodyellow;">
                    {% if user in product.choose_users.all %}
                        찜풀기<br>
                    {% else %}
                        찜하기<br>
                    {% endif %}
                </button>
            </form>
        </div>
        <br>
    {% endfor %}
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        body {
            background-image: url(https://i.pinimg.com/originals/16/f0/c8/16f0c8e693627d504d0e1ba49bdd52df.gif);
            background-size: cover;
            
        }
        .login-button {
            margin-right: 20px;
            margin-left: 20px;
            background-color: rgb(122, 135, 255);
            border:none;
        }
        .nav-links {
            background-color: rgb(122, 135, 255);
            border-radius: 8px;
            padding: 6px 10px;
            margin-right: 20px;
            margin-left: 20px;
            color: rgb(65, 56, 65);
        }
        .btn-secondary{
            background-color: rgb(253, 96, 96);
            border:none;
        }
    </style>
    {% block head %}{% endblock head %}
</head>
<body>
    <div class="container mt-5">
        <h2 class="mb-3">
            <p class="text-light">집에 가고 싶어요</p>
        </h2>
        <nav class="nav  dark p-1 rounded">
            <a class="nav-link" href="{% url 'products:list' %}" style="background-color: lightgoldenrodyellow; color: rgb(247, 0, 255); border-radius: 8px;
            padding: 7px 10px; ">홈</a>
            {% if user.is_authenticated %}
                <a class="nav-links" href="{% url 'accounts:profile' user.id %}">{{ user.username }}</a>
                <form class="d-flex align-items-center" action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <button class="btn btn-danger">로그아웃</button>
                </form>
            {% else %}
                <a href="{% url 'accounts:login' %}" class="btn btn-primary login-button">로그인</a>
                <a class="btn btn-secondary" href="{% url 'accounts:signup' %}">회원가입</a>
            {% endif %}
        </nav>
        <ul class="list-group my-3">
            {% for message in message %}
                <li class="list-group-item">{{ message }}</li>
            {% endfor %}
        </ul>
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>